import Head from "next/head";
import { GetServerSideProps } from "next";

import { Inter } from "@next/font/google";

import { Home } from "@/components";
import { Events, Category } from "@/types";

const inter = Inter({ subsets: ["latin"] });

interface Prop {
  categories: Category[];
}

const HomePage: React.FC<Prop> = ({ categories }) => {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home categories={categories} />
    </>
  );
};

export default HomePage;

export const getServerSideProps: GetServerSideProps<Prop> = async (context) => {
  // ...
  const data: Events = await import("../data/events.json");
  const { events_categories } = data;
  return {
    props: {
      categories: events_categories,
    },
  };
};
